### ISSUE TITLE
Pair with sunshine / Add computer manually

### ISSUE THREAD

**Issue by BrachystochroneSD** [clarkemw/moonlight-embedded-launcher#12]
Hello,

Firstly, thanks for this wonderful addon. 

I would like to pair your addon with my setup of [sunshine](https://github.com/loki-47-6F-64/sunshine) host. Unfortunately, your addon can't detect it automatically. 
I was able to pair it correctly with the "Moonlight" android app (from f-droid) by entering manually the ip address of my host. 

Maybe it would be possible to implement an option to 'add PC manually' like in the f-droid app? Or maybe it is not the same problem here?
Is your addon save the host in a config file? Does-it save the ip address? If yes, I could create one manually, as a workaround.

**Comment by BrachystochroneSD** [comment]
Hello,

My problem of sunshine not begin detected if easily fixable by launching the avahi service. It now works like a charm.
Feel free to implement the "add PC manually" feature if you think it can be useful. But normally it is not needed

**Comment by clarkemw** [comment]
Good to hear that it worked.  I was actually just looking into this and I think I will implement the custom IP capability.  Did you need to add any of the flags mentioned in this github issue in order for sunshine to stream correctly?
https://github.com/moonlight-stream/moonlight-embedded/issues/806

**Comment by BrachystochroneSD** [comment]
I haven't changed anything in the config of the moonlight-embedded in the docker files or the settings of your addon. It worked as soon as I've launched the avahi daemon in the host computer.
Not sure where to put these flags anyway, I am not familiar with docker but I have checked in the moonlight.conf in overlay2/cc0e666949cc0cbfd602aa5122fffe78c8e47e232440f456d0822b3e10231b78/diff/usr/local/etc/moonlight.conf and the "sops" option is set to "true". 

If you need it. I am ready to do some tests with the custom IP implementation.

**Comment by clarkemw** [comment]
Here's the first implementation of adding a custom IP.  Please let me know how it works for you.  The new settings can be found in the addon gui at: `Configure/Settings/Host Detection`.  
Set the `Auto-Detect` flag to `False` and specify an IP.  If you set `Auto-Detect` to `True` the IP will be ignored and it will revert back to the old setup where it uses avahi to find the gamestream host.

https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/v1.1-alpha/script.moonlight-embedded-launcher-1.1-alpha.zip

**Comment by BrachystochroneSD** [comment]
It works perfectly! Nice job!

**Comment by clarkemw** [comment]
Integrated changes from #14 to finalize this.  See the v1.1 release.  Thanks for your help in testing the changes out.
