### ISSUE TITLE
How to play audio on host instead of streaming to client?

### ISSUE THREAD

**Issue by Frostoman** [clarkemw/moonlight-embedded-launcher#13]
Hi.

There is no option for this in your script, but I know, it should be in moonlight.conf. I was find three copies of this file on my RP's SD card, but changes has no effect.

Can you add this function to script, or help me find where proper moonlight.conf file stored, to do changes in it?

Thank you.

**Comment by clarkemw** [comment]
Hello it looks like there is a command line flag that can be added to accomplish this.  I added a new settings field where you can pass in custom arguments. Can you download/install the test version of the plugin linked below and add `-localaudio` (make sure to include the dash in the front) to the new field in `Settings/Advanced/Custom Flags for Moonlight Embedded`
https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/v1.1-alpha2/script.moonlight-embedded-launcher-1.1-alpha2.zip

Theoretically this new settings input should allow you to pass in any flags (space separated) from the full listing of command line settings found at the link below but I haven't done a ton of testing.
https://github.com/moonlight-stream/moonlight-embedded/wiki/Usage

**Comment by Frostoman** [comment]
It works! I added two space separated flags, -localaudio and -720, and both are working.

Now I can play normally using my headset connected to PC, without doing all these manipulations in Windows sound settings, with NVIDIA audio output turn off each time. I don't know why, but I can't switch audio output, if NVIDIA audio output using. Only fully turn off helps. Maybe it's some Windows issue.

Thank you very much for this implementation of moonlight support in Kodi. You're awesome!

**Comment by clarkemw** [comment]
Happy to help. Just FYI you can also set the resolution in the addon under `Settings/Video/Resolution` instead of using the custom flag. I'm not sure how moonlight will handle conflicting settings between there and the custom flags.

**Comment by Frostoman** [comment]
Yes, of course. I used flags only for testing, how they work together. And they have priority. My resolution is 1080p, but with flag it downgrades to 720p.
