### ISSUE TITLE
Unable to pair with host, error during list

### ISSUE THREAD

**Issue by blacklaboratory** [clarkemw/moonlight-embedded-launcher#19]
Hello, thanks for this embedded-launcher for libreelec ! It used to work like a charm but due to the poor wifi of my pi3b+ (libreelec 9.2.8 kodi 18.9) I installed a router as a bridge wich my pi is now connected from via ethernet.

Since then, launching moonlight returned me to an error so I decided to reinstall it with this link : [https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/refs/heads/main.zip](https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/refs/heads/main.zip) and docker from scratch.

At step 5 from the instructions, the pairing process does not work. It closes immediately and I can't figure out why. If I tried to click play games, it return me this error : 
**Error during list**
docker : error response from daemon : error creating overlay mount to
/storage/.kodi/userdata/addon_data/service.system.docker/docker
no such file or directory.
See 'docker run --help'.

Maybe it's a network issue caused by my new router ? it's strange cause I currently can access my pi via SSH to 192.168.1.92 and I also tried deactivating autoscan for gamehost and writing my pc ip adress : 192.168.1.31. So they seem to be on the same local network ? Also my pc works as a SMB windows share server as all my medias are stocked in it works with the pi.

Here is a link to my debug log : [http://ix.io/493G](http://ix.io/493G)

Thank you for any help you can give with this issue :)

Edit: added libreelec version

**Comment by clarkemw** [comment]
Can you confirm that you rebooted after installing/enabling Docker? I think LibreELEC needs to load some Docker libraries during system startup to function correctly.  After confirming can you SSH to the Pi and see if you see `moonlight-home` when running the following command:
`docker volume ls`

**Comment by blacklaboratory** [comment]
Yes i rebooted after installing docker, also after deinstalling before the severals reinstalls from scratch i tried. 

the command line return me 

> DRIVER              VOLUME NAME
local               moonlight-home

**Comment by blacklaboratory** [comment]
Somes lines that might be interesting in the log, I'm quit noobish with libreelec and Linux in general sorry to bother for something that maybe easy to fix

<details>
<summary>Click to expand</summary>

> 2022-08-29 18:43:13.319 T:1937721792   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
2022-08-29 18:43:13.408 T:1542341504    INFO: CPythonInvoker(8, /storage/.kodi/addons/script.moonlight-embedded-launcher/addon.py): script aborted
2022-08-29 18:43:13.408 T:1542341504   DEBUG: onExecutionDone(8, /storage/.kodi/addons/script.moonlight-embedded-launcher/addon.py)
2022-08-29 18:43:13.421 T:1542341504    INFO: Python interpreter stopped


> Apr 11 18:28:40 LibreELEC avahi-daemon[322]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.92.
Apr 11 18:28:40 LibreELEC avahi-daemon[322]: New relevant interface eth0.IPv4 for mDNS.
Apr 11 18:28:40 LibreELEC avahi-daemon[322]: Registering new address record for 192.168.1.92 on eth0.IPv4.
Apr 11 18:28:40 LibreELEC connmand[315]: Setting domainname to lan
Apr 11 18:28:40 LibreELEC connmand[315]: eth0 {add} address 192.168.1.92/24 label eth0 family 2
Apr 11 18:28:40 LibreELEC connmand[315]: eth0 {add} route 192.168.1.0 gw 0.0.0.0 scope 253 <LINK>
Apr 11 18:28:40 LibreELEC connmand[315]: eth0 {add} route 192.168.1.254 gw 0.0.0.0 scope 253 <LINK>
Apr 11 18:28:40 LibreELEC connmand[315]: eth0 {add} route 0.0.0.0 gw 192.168.1.254 scope 0 <UNIVERSE>
Apr 11 18:28:40 LibreELEC systemd[1]: Started Wait on network.
Apr 11 18:28:40 LibreELEC systemd[1]: Reached target Network is Online.
Apr 11 18:28:40 LibreELEC systemd[1]: Starting Samba NMB Daemon...
Apr 11 18:28:40 LibreELEC connmand[315]: eth0 {add} route 82.165.8.211 gw 192.168.1.254 scope 0 <UNIVERSE>
Apr 11 18:28:40 LibreELEC connmand[315]: ntp: adjust (jump): +106791139.390456 sec
Aug 29 18:41:00 LibreELEC systemd[1]: Started Wait For Kernel Time Synchronized.
Aug 29 18:41:00 LibreELEC systemd[1]: Reached target System Time Synchronized.
Aug 29 18:41:00 LibreELEC connmand[315]: eth0 {del} route 82.165.8.211 gw 192.168.1.254 scope 0 <UNIVERSE>

192.168.1.254 is my modem local IP


> Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.552054989+02:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.127\n": exit status 1"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.552221969+02:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.553026552+02:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.553891812+02:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.557237386+02:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /storage/.kodi/userdata/addon_data/service.system.docker/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.557346969+02:00" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.557478011+02:00" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.127\n": exit status 1"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.557527802+02:00" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /storage/.kodi/userdata/addon_data/service.system.docker/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561328740+02:00" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561470042+02:00" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561650095+02:00" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561727751+02:00" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561798949+02:00" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.561929001+02:00" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.562066449+02:00" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.562151553+02:00" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.562230667+02:00" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.562324886+02:00" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.562813845+02:00" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.563064886+02:00" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.564790720+02:00" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.564957543+02:00" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565137699+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565213324+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565289209+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565405303+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565490512+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565563532+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565652439+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565762230+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.565834001+02:00" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.566125251+02:00" level=warning msg="failed to load plugin io.containerd.internal.v1.opt" error="mkdir /opt/containerd: read-only file system"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.566180512+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.566261866+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.566337074+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.566412074+02:00" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.574717179+02:00" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.575048065+02:00" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.575132440+02:00" level=info msg="containerd successfully booted in 0.042580s"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.597742963+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x4caa200, READY" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.704188182+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.704317452+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.705010369+02:00" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.705181150+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.705434640+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x4cb4090, CONNECTING" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.705655630+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.705710005+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.706200369+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x4cb4090, READY" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.706498078+02:00" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.706606619+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.706772244+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x4cb41e0, CONNECTING" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.707511880+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x4cb41e0, READY" module=grpc
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.834006684+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.834766111+02:00" level=warning msg="Your kernel does not support swap memory limit"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.834948924+02:00" level=warning msg="Your kernel does not support cgroup cpu shares"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835009965+02:00" level=warning msg="Your kernel does not support cgroup cfs period"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835066215+02:00" level=warning msg="Your kernel does not support cgroup cfs quotas"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835121268+02:00" level=warning msg="Your kernel does not support cgroup rt period"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835185799+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835244966+02:00" level=warning msg="Your kernel does not support cgroup blkio weight"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835298091+02:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835404966+02:00" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835462622+02:00" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835519966+02:00" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835577986+02:00" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.835995955+02:00" level=warning msg="mountpoint for pids not found"
Aug 29 18:41:01 LibreELEC dockerd[326]: time="2022-08-29T18:41:01.841747206+02:00" level=info msg="Loading containers: start."
Aug 29 18:41:01 LibreELEC kernel: bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
Aug 29 18:41:01 LibreELEC kernel: Bridge firewalling registered
Aug 29 18:41:02 LibreELEC dockerd[326]: time="2022-08-29T18:41:02.276743134+02:00" level=warning msg="Could not load necessary modules for IPSEC rules: Running modprobe xfrm_user failed with message: `modprobe: WARNING: Module xfrm_user not found in directory /lib/modules/4.19.127`, error: exit status 1"
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {create} index 4 type 1 <ETHER>
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {update} flags 4098 <DOWN>
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 address 56:88:C9:34:EE:A5 mtu 1500
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {create} index 4 type 1 <ETHER>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {update} flags 4098 <DOWN>
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 address 02:42:05:7F:35:BA mtu 1500
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 address 56:88:C9:34:EE:A5 mtu 1500
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 address 02:42:05:7F:35:BA mtu 1500
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {add} address 172.17.0.1/16 label docker0 family 2
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {update} flags 4099 <UP>
Aug 29 18:41:02 LibreELEC kernel: IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 address 02:42:05:7F:35:BA mtu 1500
Aug 29 18:41:02 LibreELEC connman-vpnd[270]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC avahi-daemon[322]: Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Aug 29 18:41:02 LibreELEC avahi-daemon[322]: New relevant interface docker0.IPv4 for mDNS.
Aug 29 18:41:02 LibreELEC avahi-daemon[322]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {update} flags 4099 <UP>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 address 02:42:05:7F:35:BA mtu 1500
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {newlink} index 4 operstate 2 <DOWN>
Aug 29 18:41:02 LibreELEC connmand[315]: docker0 {add} route 172.17.0.0 gw 0.0.0.0 scope 253 <LINK>
Aug 29 18:41:02 LibreELEC dockerd[326]: time="2022-08-29T18:41:02.677838383+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 29 18:41:02 LibreELEC dockerd[326]: time="2022-08-29T18:41:02.951734660+02:00" level=info msg="Loading containers: done."
Aug 29 18:41:03 LibreELEC dockerd[326]: time="2022-08-29T18:41:03.442310386+02:00" level=info msg="Docker daemon" commit=18.09.7 graphdriver(s)=overlay2 version=18.09.7
Aug 29 18:41:03 LibreELEC dockerd[326]: time="2022-08-29T18:41:03.446313564+02:00" level=info msg="Daemon has completed initialization"
Aug 29 18:41:03 LibreELEC dockerd[326]: time="2022-08-29T18:41:03.500461902+02:00" level=info msg="API listen on /var/run/docker.sock"
Aug 29 18:41:03 LibreELEC systemd[1]: Started Docker Application Container Engine.
Aug 29 18:41:03 LibreELEC systemd[1]: Reached target Multi-User System.
Aug 29 18:41:03 LibreELEC systemd[1]: Reached target Graphical Interface.
Aug 29 18:41:03 LibreELEC systemd[1]: Starting Kodi user autostart script...
Aug 29 18:41:03 LibreELEC systemd[1]: Started Kodi user autostart script.
Aug 29 18:41:03 LibreELEC systemd[1]: Starting Kodi Media Center...
Aug 29 18:41:03 LibreELEC systemd[1]: Started Kodi Media Center.
Aug 29 18:41:03 LibreELEC systemd[1]: Reached target Kodi Mediacenter Interface.
Aug 29 18:41:03 LibreELEC systemd[1]: Startup finished in 2.227s (kernel) + 8.181s (userspace) = 10.408s.
Aug 29 18:41:23 LibreELEC nmbd[344]: [2022/08/29 18:41:23.432293,  0] ../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
Aug 29 18:41:23 LibreELEC nmbd[344]:   *****
Aug 29 18:41:23 LibreELEC nmbd[344]: 
Aug 29 18:41:23 LibreELEC nmbd[344]:   Samba name server LIBREELEC is now a local master browser for workgroup WORKGROUP on subnet 192.168.1.92
Aug 29 18:41:23 LibreELEC nmbd[344]: 
Aug 29 18:41:23 LibreELEC nmbd[344]:   *****
Aug 29 18:41:25 LibreELEC dockerd[326]: time="2022-08-29T18:41:25.435798515+02:00" level=error msg="error unmounting /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/a201cedc388c99e62902cef0883215df422d2d63541545079e1172a04cf1f172-init/merged: invalid argument" storage-driver=overlay2
Aug 29 18:41:25 LibreELEC dockerd[326]: time="2022-08-29T18:41:25.437452108+02:00" level=error msg="Handler for POST /v1.39/containers/create returned error: error creating overlay mount to /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/a201cedc388c99e62902cef0883215df422d2d63541545079e1172a04cf1f172-init/merged: no such file or directory"
Aug 29 18:41:25 LibreELEC kernel: overlayfs: failed to resolve '/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/l/LSVE4I2M75BY2YGPEGOANG4D5O': -2
Aug 29 18:41:28 LibreELEC dockerd[326]: time="2022-08-29T18:41:28.236524523+02:00" level=error msg="error unmounting /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/706ed330227ab3b1fd9235d92b6d4cfd3dfa31b95069c9e6b37444c87ab8aa5f-init/merged: invalid argument" storage-driver=overlay2
Aug 29 18:41:28 LibreELEC kernel: overlayfs: failed to resolve '/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/l/LSVE4I2M75BY2YGPEGOANG4D5O': -2
Aug 29 18:41:28 LibreELEC dockerd[326]: time="2022-08-29T18:41:28.239792179+02:00" level=error msg="Handler for POST /v1.39/containers/create returned error: error creating overlay mount to /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/706ed330227ab3b1fd9235d92b6d4cfd3dfa31b95069c9e6b37444c87ab8aa5f-init/merged: no such file or directory"
Aug 29 18:41:28 LibreELEC systemd[1]: systemd-hostnamed.service: Succeeded.
Aug 29 18:42:41 LibreELEC dockerd[326]: time="2022-08-29T18:42:41.636506263+02:00" level=error msg="error unmounting /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/28f78b8c904f1038502f4a25774a28397100faf266280c68023f994627880304-init/merged: invalid argument" storage-driver=overlay2
Aug 29 18:42:41 LibreELEC dockerd[326]: time="2022-08-29T18:42:41.638117929+02:00" level=error msg="Handler for POST /v1.39/containers/create returned error: error creating overlay mount to /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/28f78b8c904f1038502f4a25774a28397100faf266280c68023f994627880304-init/merged: no such file or directory"
Aug 29 18:42:41 LibreELEC kernel: overlayfs: failed to resolve '/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/l/LSVE4I2M75BY2YGPEGOANG4D5O': -2
Aug 29 18:42:44 LibreELEC dockerd[326]: time="2022-08-29T18:42:44.571319472+02:00" level=error msg="error unmounting /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/11e0890ad0392260223ab58f2b67487bab5e2cf0904eac2550816a22931850db-init/merged: invalid argument" storage-driver=overlay2
Aug 29 18:42:44 LibreELEC kernel: overlayfs: failed to resolve '/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/l/LSVE4I2M75BY2YGPEGOANG4D5O': -2
Aug 29 18:42:44 LibreELEC dockerd[326]: time="2022-08-29T18:42:44.573652336+02:00" level=error msg="Handler for POST /v1.39/containers/create returned error: error creating overlay mount to /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/11e0890ad0392260223ab58f2b67487bab5e2cf0904eac2550816a22931850db-init/merged: no such file or directory"
Aug 29 18:44:57 LibreELEC sshd[769]: Accepted password for root from 192.168.1.31 port 64488 ssh2

</details>

Lot of errors that I don't understand at all ^^'

**Comment by blacklaboratory** [comment]
Ok so my newly bought router just broke and it gives me the idea to test moonlight as it worked before with the pi internal wifi and still doesn't work even after reinstalling everything and so forth.  Will try reinstalling libreelec from scratch see if it works.

**Comment by clarkemw** [comment]
To help narrow things down a  bit are you able to run this command via SSH on the Pi?
`docker run --rm --name moonlight -t -v moonlight-home:/home/moonlight-user -v /var/run/dbus:/var/run/dbus clarkemw/moonlight-embedded-raspbian help`
It should just give a listing of the flags that moonlight uses and exit

If that works please try the following command via SSH on the Pi (and make sure your gamestream host is on and connected to the same network):
`avahi-browse -ta`
One of the return arguments should have `_nvstream._tcp` if the Pi is able to find the gamestream host.

**Comment by blacklaboratory** [comment]
the first command line didn't work it returned me 

> docker: Error response from daemon: error creating overlay mount to /storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/68626854f29f59d7f8678e90e64ddf0b102fafde8f455e9e1caa9037ee71aa55-init/merged: no such file or directory.

Edit : also tried to rollback to previous nvidia driver because there was an update recently and still the same
Also tried to install on a fresh libreelec install on a different SD card and it works, the installation was significantly longer !

Edit2 : FOUND IT ! was wondering why it worked on a fresh install of libreelec but not on mine, and the error returned by the command line made me search on files directories. I noticed that service.system.docker was still in addon_data after uninstalling the add-on. It didn't work to delete the folder with kodi's GUI so i went with ssh :

`cd .kodi/userdata/addon_data`
`rm -rf service.system.docker/`

And that's it, reinstalled docker and moonlight and it's working again 

Thanks for your time, your help, and for this amazing add-on 👍

**Comment by clarkemw** [comment]
Glad you got it sorted. Interesting that Docker package managed to get itself into a broken state. If you run into that again it might be worth reporting to https://github.com/LibreELEC/LibreELEC.tv since they maintain the Docker package in there.
