### ISSUE TITLE
Incorrect link in installation guide

### ISSUE THREAD

**Issue by Frostoman** [clarkemw/moonlight-embedded-launcher#20]
Hello. Are you still supporting this project? The link to the archive in the installation guide does not work. Please repair it. In case someone wants to install this add-on. By the way, it works perfectly with the Sunshine service, analog of Nvidia Gamestream from the Moonlight developers.

**Comment by Frostoman** [comment]
Okay, I've done a little research and I think I've figured out what the problem might be. NVIDIA has stopped supporting local streaming, so it might not work in newer versions of GeForce Experience. About that, your add-on works with a streaming service from the Moonlight developers called (drum roll) Sunshine. https://github.com/LizardByte/Sunshine

**Comment by Frostoman** [comment]
Please repair link to the archive with script v1.1

**Comment by ivanromeroprog** [comment]
This URL works aparently, github broke backwards compatibility with urls?

https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/refs/tags/v1.1/script.moonlight-embedded-launcher-1.1.zip

**Comment by Frostoman** [comment]
I don't know what happened with github, but the link on the page with instructions for installing the addon "wget https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/v1.1/script.moonlight-embedded-launcher-1.1.zip" gives an error

`
Server:~ # wget https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/v1.1/script.moonlight-embedded-la
uncher-1.1.zip
Connecting to github.com (140.82.121.3:443)
wget: can't open 'script.moonlight-embedded-launcher-1.1.zip': File exists
`

The new link works. It would be nice if you could point it out in the instructions. Thanks.

`
Server:~ # wget https://github.com/clarkemw/script.moonlight-embedded-launcher/archive/refs/tags/v1.1/script.moonlight-e
mbedded-launcher-1.1.zip
Connecting to github.com (140.82.121.3:443)
Connecting to codeload.github.com (140.82.121.9:443)
saving to 'script.moonlight-embedded-launcher-1.1.zip'
script.moonlight-emb 100% |************************************************************************|  523k  0:00:00 ETA
'script.moonlight-embedded-launcher-1.1.zip' saved
`

Also, if you wish, you can remove the part about GeForce Experience from the instructions (apparently, NVIDIA has stopped supporting streaming functionality and it no longer works with the addon) and replace it with a link to the Sunshine project, which supports streaming on NVIDIA, AMD, and Intel video cards.

https://github.com/LizardByte/Sunshine

Maybe this will be useful to someone :)

Thanks for the great addon, I've been using it for years on my Raspberry Pi3 to stream games from my PC to the TV to play comfortably sitting on the couch in front of the big screen :)

**Comment by clarkemw** [comment]
Corrected with commit fdfc168

Thanks!
