### ISSUE TITLE
Setting stream parameters

### ISSUE THREAD

**Issue by krisrok** [clarkemw/moonlight-embedded-launcher#3]
Is there a way to set the resolution/bitrate/compression etc of the stream?

**Comment by peetie2k** [comment]
not yet in the code, though I think this can be introduced. Look here, there are flags available to switch between H.264/H.265, 1080i/4K, and you can control the FPS. I'll probably add that to the config of the Add-On, and this config can then be passed to the container launch.
https://github.com/irtimmer/moonlight-embedded/wiki/Usage

**Comment by clarkemw** [comment]
It looks like we can easily add this to the settings.xml file in the addon, which will allow the user to select various flags.  I'll try to get that in once I pull in @peetie2k 's latest PR.  We might need to hold off on an h264/h265 switch for now since moonlight-embedded doesn't support h265 on rpi to my knowledge.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>  
<settings>  
    <category label="Video">  
       <setting type="select" id="resolution" label="Resolution" values="720|1080|1440|2160" default="1080"/>  
       <setting type="slider" id="fps" label="Frames Per Second" range="30,10,120" default="60" option="int"/>  
    </category>  
</settings>
```

Then we can access these values in main.py using: 
```
import xbmcaddon  
addon = xbmcaddon.Addon(id='script.moonlight-embedded-launcher')  
fps = addon.getSetting('fps')
```

More details to work out but I think this should be fairly simple to implement.

**Comment by krisrok** [comment]
thanks for your replies. the settings.xml approach seems most viable. 

nonetheless:
@peetie2k can you access the docker image‘s files when it‘s not mounted/started? sorry never worked with docker before. 

i‘d like to quickly check if my 5ghz wifi (rating of only 44 in libreelec) is capable enough for reliable streaming with lower bitrate/framerate as i cannot run an ethernet cable there.

**Comment by peetie2k** [comment]
Files are always "burned" into a docker image. The link above shows you the command line options which can be passed to the executable which is called. If you want to test the things, you can simply adopt the call command in
https://github.com/clarkemw/moonlight-embedded-launcher/blob/main/script.moonlight-embedded-launcher/bin/launch_moonlight.sh
To reflect your resolution/fps. You need to rebuild and install the kodi add-on and it should respect your changes.

**Comment by krisrok** [comment]
thanks for the pointers! as it‘s python i think rebuilding the addon isn‘t even neccessary, just reinstalling is sufficient i guess?

**Comment by peetie2k** [comment]
You need to adopt the shell script starting the container. If you adopt that sh file at the right location (after instalatlion/unzipping), you don't need to do anything.

The install script will create that zip file representing the kodi addon, so if you clone the repo and adopt the sh file I linked, you'd need to (re)build the zip for the add-on again (either by executing the install.sh again, or by manually running the zip command contained in it)

**Comment by krisrok** [comment]
for completeness sake:

`nano .kodi/addons/script.moonlight-embedded-launcher/bin/launch_moonlight.sh`
brings you there

720p stream works way better btw, so not all hope is lost this setup might work for me after all :)

**Comment by krisrok** [comment]
here‘s a list of command line options, might be incomplete/outdated or not 100% applicable for the embedded version though

https://github.com/moonlight-stream/moonlight-qt/issues/30#issuecomment-422133470

**Comment by clarkemw** [comment]
Just pushed an update that gives some basic settings functionality for fps/resolution and bitrate. Feel free to download and test it out.  Please let me know if you find any issues. Haven't made it into a release yet so just do this:
```
wget https://github.com/clarkemw/moonlight-embedded-launcher/archive/main.zip
unzip main.zip
cd moonlight-embedded-launcher-main
zip -r test.zip script.moonlight-embedded-launcher
```
Then go in Kodi and install that test.zip file.  No need to rerun install.sh.

**Comment by krisrok** [comment]
Finally came back to this: Works like a charm, thanks!
