### ISSUE TITLE
Game even if select dialog is cancelled...

### ISSUE THREAD

**Issue by nicolaspernoud** [clarkemw/moonlight-embedded-launcher#4]
Hi,

Thanks for that great work.
Just a little hiccup : the game starts event if the select dialog is cancelled.
Maybe adding something like : 
```python
    if gameIdX == -1:
        sys.exit()
```
could do the trick ?

Thanks,

**Comment by clarkemw** [comment]
Thank you for the suggestion I added this into the 0.4 release.  The old 0.3 release would let you cancel via keyboard/remote control on the "Select OK to launch Steam" screen, but it wasn't very clear to the end user.  This new setup is much more robust/straightforward.
