### ISSUE TITLE
Can Not Find Docker

### ISSUE THREAD

**Issue by katjap** [clarkemw/moonlight-embedded-launcher#6]
System: Raspberry Pi 3
OS: LibreElec 9.2.6
Docker Plugin Installed: 9.2.0.127

Problem: Install script says "Can Not Find Docker" even though Docker is installed and ps aux shows dockerd as running

**Comment by clarkemw** [comment]
I think this might be a path issue.  Did your ssh session where you are running install.sh start prior to installing the Docker add-on in Kodi?  If so, please try opening a new ssh session (close the existing one completely) and rerun install.sh.

If that doesn't work please check your ~/.bash_profile or ~/.bashrc  and make sure you aren't overwriting the PATH variable.

**What I think happened here:**
When you open a new terminal session LibreElec will execute /etc/profile.d/99-kodi.conf.  This loops through all the installed Kodi addons and puts them on the users path so they can be called from the command line.  This would not get re-executed in your current session if you were to go into Kodi and install a new addon.  By starting a new session you ensure that the latest addons are put on your path. I can make a tweak to the installer script to re-execute this step so this doesn't happen in the future.

**Comment by katjap** [comment]
solved. thank you.
