### ISSUE TITLE
Not launching due to RTSP message too long

### ISSUE THREAD

**Issue by clarkemw** [clarkemw/moonlight-embedded-launcher#8]
After the latest GeForce Experience update (3.22.0.28) moonlight-embedded will crash with the following error, which breaks this Kodi addon:
`Starting RTSP handshake...RTSP message too long
RTSP DESCRIBE request failed: -1
failed: -1`

This is currently being tracked in https://github.com/irtimmer/moonlight-embedded/issues/810

Once that gets resolved I will update this plugin.  In the meantime downgrading GeForce Experience appears to be the only workaround.

**Comment by unalkalkan** [comment]
Until the Debian package pushed, you can make it work by compiling the master of the repository in the Dockerfile. Here's the [Dockerfile](https://gist.github.com/unalkalkan/c998b6a7ecb81c2dd09818f00d99b6b3) i prepared.

**Comment by clarkemw** [comment]
@unalkalkan your Dockerfile works great. Do you mind if I incorporate it into the next release?

**Comment by unalkalkan** [comment]
I'd love to add it as a PR and be a contributor of this repository if its good for you as well. How do you plan to add this Dockerfile? Do you think we should replace the current one or add it as an another Dockerfile

**Comment by clarkemw** [comment]
@unalkalkan That would be perfect. I'm leaning towards just replacing the current Dockerfile with yours. I don't think the apt packages for moonlight-embedded are going to get updated anytime soon. Your approach of building from source seems to work pretty well with the only downside being a slightly longer installation time. If we run into stability issues (breaking changes etc) we could update the Dockerfile to clone and revert back to a specific commit id, but that might not be necessary for now.

**Comment by peetie2k** [comment]
Instead of building the Docker image locally while installing the kodi addon, wouldn't it make sense to just push it to the public docker repo and make use of that? By that, you don't need to update the kodi part if there is any change in moonlight and you save time as you don't need to build it at install but just make use of it...

**Comment by clarkemw** [comment]
That's a good thought.  I did some digging on Docker Hub. It looks like we need to split the build Dockerfile into a separate repo (using @unalkalkan's file) that Docker Hub can reference.  Then the Dockerfile in this repo could just do a pull from that image.  

@unalkalkan can you submit your Dockerfile as a PR for this new repo? https://github.com/clarkemw/moonlight-embedded-raspbian-docker

**Edit:**
Created a new branch that works w/ a Docker Hub image pull:
https://github.com/clarkemw/moonlight-embedded-launcher/tree/dockerhub
Pulls from this image (still builds from the apt packages...will update with the build from source once I get the PR for the new Dockerfile):
https://hub.docker.com/r/clarkemw/moonlight-embedded-raspbian

**Comment by unalkalkan** [comment]
Seems nice. Just created the PR to that repo, @clarkemw.

**Comment by clarkemw** [comment]
Got everything working again. Please see release v0.5.  Rerun install.sh and reinstall the addon from zip to complete the update.
