### ISSUE TITLE
RPi 4 issues?

### ISSUE THREAD

**Issue by krisrok** [clarkemw/moonlight-embedded-launcher#9]
In the readme you write under Troubleshooting there are "issues on Raspberry Pi 4 devices". Can you elaborate on what they are? The other project you linked only works for Libreelec 10+ and might still not be an option for most of us for a while.

I've set your addon up and tested some games for a few minutes via ethernet. It worked so well I immediately ordered a long enough cable for a permanent tethered connection.

Are there any issues in the long run though? Connection resets or something like that?

Also, maybe this helps someone else. I ran into an docker issue: You have make sure to install the second-latest version of docker as of now (I think it was *26 instead of *27 but i'm not too sure). Otherwise Kodi just restarted when pressing "Play game".

**Comment by peetie2k** [comment]
I‘ve played RDR2, the whole campaign with an Xbox 360 controller without any hiccups or connection aborts on a pi4.

**Comment by clarkemw** [comment]
I haven't personally run this plugin with a RPI4 but that comment was more directed at RPI4/LibreELEC 10 users. I'll update the README accordingly.

Also I'll try to look into that Docker issue when I get a chance.  Were there any error messages?

**Comment by clarkemw** [comment]
README updated to reflect the above discussion
